VERSION = 0.9

export DESTDIR =

# all the following variables will be prepended by $(DESTDIR) upon install

export OCAMLLIBDIR := $(shell ocamlc -where)
export BINDIR  = /usr/bin
export LIBDIR = /usr/lib
export INCDIR = /usr/include
export PCDIR   = $(LIBDIR)/pkgconfig
