language: node_js
node_js:
  - "10.13.0"

matrix:
  include:
    - os: osx
      env: OCAML=4.07.1
    - os: osx
      env: ESY_BUILD=YES ESY__CACHE=/home/travis/.esy
    - os: linux
      env: OCAML=4.02.3
    - os: linux
      env: OCAML=4.02.3+buckle-master
    - os: linux
      env: OCAML=4.03.0
    - os: linux
      env: OCAML=4.04.2
    - os: linux
      env: OCAML=4.05.0
    - os: linux
      env: OCAML=4.06.1
    - os: linux
      env: OCAML=4.07.1
    - os: linux
      env: OCAML=ocaml-variants.4.08.0+beta1 REPOSITORIES=--repositories=default,beta=git+https://github.com/ocaml/ocaml-beta-repository.git
    - os : linux
      env: ESY_BUILD=YES ESY__CACHE=/home/travis/.esy

  fast_finish: true

cache:
  directories:
  - /usr/local/Cellar/opam
  - /usr/local/Cellar/tidy-html5
  - $HOME/travis/.opam
  - $HOME/travis/.esy
  - $HOME/travis/.nvm
  - ./_build/default

install:
  - ./test/ci/install-deps.sh
  - "if [[ $OCAML ]]; then eval `opam env`; fi"
  - ./test/ci/print-versions.sh

before_script:
  - ./test/ci/clean-scratch.sh

script: travis_wait 20 ./test/ci/build.sh

notifications:
  email:
    recipients:
      - antonbachin@yahoo.com
    on_success: always
    on_failure: always
