language: generic

env:
  - OCAML=4.02.3
  - OCAML=4.02.3+buckle-master
  - OCAML=4.03.0
  - OCAML=4.04.2
  - OCAML=4.05.0
  - OCAML=4.06.1
  - OCAML=4.07.0

before_script:
  - sudo add-apt-repository -y ppa:robert7/nixnote21
  - sudo add-apt-repository -y ppa:avsm/ocaml42+opam12
  - sudo apt-get update
  - sudo apt-get install opam tidy
  - "opam init -y --compiler=$OCAML"
  - eval `opam config env`

script:
  - opam pin add -y --no-action odoc .
  - opam install -y --deps-only odoc
  - make test
  - opam pin add -y --dev-repo dune
  - make dune-test

notifications:
  email:
    recipients:
      - antonbachin@yahoo.com
    on_success: always
    on_failure: always
