debian-9-arm64:
  image: ocaml/opam2:debian-9-opam
  stage: build
  only:
    - /^master$/
  script:
  - make
  - mkdir -p ocaml-platform/4.07.0-1/debian-9/arm64 && cp _build/default/output/* ocaml-platform/4.07.0-1/debian-9/arm64
  artifacts:
    paths:
      - ocaml-platform
  tags:
    - docker
    - arm64
debian-9-ppc64le:
  image: ocaml/opam2:debian-9-opam
  stage: build
  only:
    - /^master$/
  script:
  - make
  - mkdir -p ocaml-platform/4.07.0-1/debian-9/ppc64le && cp _build/default/output/* ocaml-platform/4.07.0-1/debian-9/ppc64le
  artifacts:
    paths:
      - ocaml-platform
  tags:
    - docker
    - ppc64le
debian-9-amd64:
  image: ocaml/opam2:debian-9-opam
  stage: build
  only:
    - /^master$/
  script:
  - make
  - mkdir -p ocaml-platform/4.07.0-1/debian-9/amd64 && cp _build/default/output/* ocaml-platform/4.07.0-1/debian-9/amd64
  artifacts:
    paths:
      - ocaml-platform
  tags:
    - docker
    - amd64
ubuntu-1804-amd64:
  image: ocaml/opam2:ubuntu-18.04-opam
  stage: build
  only:
    - /^master$/
  script:
  - make
  - mkdir -p ocaml-platform/4.07.0-1/ubuntu-18.04/amd64 && cp _build/default/output/* ocaml-platform/4.07.0-1/ubuntu-18.04/amd64
  artifacts:
    paths:
      - ocaml-platform
  tags:
    - docker
    - amd64
alpine-3.7-amd64:
  image: ocaml/opam2:alpine-3.7-opam
  stage: build
  only:
    - /^master$/
  script:
  - make
  - mkdir -p ocaml-platform/4.07.0-1/alpine-3.7/amd64 && cp _build/default/output/* ocaml-platform/4.07.0-1/alpine-3.7/amd64
  artifacts:
    paths:
      - ocaml-platform
  tags:
    - docker
    - amd64
centos-7-amd64:
  image: ocaml/opam2:centos-7-opam
  stage: build
  only:
    - /^master$/
  script:
  - make
  - mkdir -p ocaml-platform/4.07.0-1/centos-7/amd64 && cp _build/default/output/* ocaml-platform/4.07.0-1/centos-7/amd64
  artifacts:
    paths:
      - ocaml-platform
  tags:
    - docker
    - amd64
fedora-28-amd64:
  image: ocaml/opam2:fedora-28-opam
  stage: build
  only:
    - /^master$/
  script:
  - make
  - mkdir -p ocaml-platform/4.07.0-1/fedora-28/amd64 && cp _build/default/output/* ocaml-platform/4.07.0-1/fedora-28/amd64
  artifacts:
    paths:
      - ocaml-platform
  tags:
    - docker
    - amd64
opensuse-42.3-amd64:
  image: ocaml/opam2:opensuse-42.3-opam
  stage: build
  only:
    - /^master$/
  script:
  - make
  - mkdir -p ocaml-platform/4.07.0-1/opensuse-42.3/amd64 && cp _build/default/output/* ocaml-platform/4.07.0-1/opensuse-42.3/amd64
  artifacts:
    paths:
      - ocaml-platform
  tags:
    - docker
    - amd64
ubuntu-16.04-arm32v7:
  stage: build
  only:
    - /^master$/
  script:
  - make
  - mkdir -p ocaml-platform/4.07.0-1/ubuntu-16.04/arm32v7 && cp _build/default/output/* ocaml-platform/4.07.0-1/ubuntu-16.04/arm32v7
  artifacts:
    paths:
      - ocaml-platform
  tags:
    - arm32v7
macos-amd64:
  stage: build
  only:
    - /^master$/
  script:
  - make
  - mkdir -p ocaml-platform/4.07.0-1/macos/amd64 && cp _build/default/output/* ocaml-platform/4.07.0-1/macos/amd64
  artifacts:
    paths:
      - ocaml-platform
  tags:
    - macos
freebsd-11-amd64:
  stage: build
  only:
    - /^master$/
  script:
  - env ASSUME_ALWAYS_YES=true pkg install gmake
  - gmake
  - mkdir -p ocaml-platform/4.07.0-1/freebsd/amd64 && cp _build/default/output/* ocaml-platform/4.07.0-1/freebsd/amd64
  artifacts:
    paths:
      - ocaml-platform
  tags:
    - freebsd
openbsd-6.3-amd64:
  stage: build
  only:
    - /^master$/
  script:
  - pkg_add gmake
  - gmake
  - mkdir -p ocaml-platform/4.07.0-1/openbsd/amd64 && cp _build/default/output/* ocaml-platform/4.07.0-1/openbsd/amd64
  artifacts:
    paths:
      - ocaml-platform
  tags:
    - openbsd
    - amd64
bytecode-only:
  image: ocaml/opam2:alpine-3.7-opam
  stage: build
  only:
    - /^master$/
  script:
  - make bytecode-only
  tags:
    - docker
    - amd64
flambda-amd64:
  image: ocaml/opam2:debian-9-opam
  stage: build
  only:
    - /^master$/
  script:
  - make flambda
  tags:
    - docker
    - amd64
flambda-ppc64le:
  image: ocaml/opam2:debian-9-opam
  stage: build
  only:
    - /^master$/
  script:
  - make flambda
  tags:
    - docker
    - ppc64le
gather-binaries:
  stage: gather
  script:
  - tar -zcvf ocaml-platform-$CI_COMMIT_SHA.tar.gz ocaml-platform
  artifacts:
    paths:
      - ocaml-platform-$CI_COMMIT_SHA.tar.gz
stages:
  - build
  - gather
