debian-9-arm64:
  image: ocaml/opam2:debian-9-opam
  stage: build
  script:
  - sudo apt-get update && sudo apt-get -y install pkg-config m4
  - opam init -ya --disable-sandboxing
  - opam install -y ocamlfind dune
  - opam exec -- make
  - mkdir -p ocaml-platform/4.07.0-1/debian-9/arm64 && cp _build/default/output/* ocaml-platform/4.07.0-1/debian-9/arm64
  artifacts:
    paths:
      - ocaml-platform
  tags:
    - docker
    - arm64
debian-9-amd64:
  image: ocaml/opam2:debian-9-opam
  stage: build
  script:
  - sudo apt-get update && sudo apt-get -y install pkg-config m4
  - opam init -ya --disable-sandboxing
  - opam install -y ocamlfind dune
  - opam exec -- make
  - mkdir -p ocaml-platform/4.07.0-1/debian-9/amd64 && cp _build/default/output/* ocaml-platform/4.07.0-1/debian-9/amd64
  artifacts:
    paths:
      - ocaml-platform
  tags:
    - docker
    - amd64
ubuntu-1804-amd64:
  image: ocaml/opam2:ubuntu-18.04-opam
  stage: build
  script:
  - sudo apt-get update && sudo apt-get -y install pkg-config m4
  - opam init -ya --disable-sandboxing
  - opam install -y ocamlfind dune
  - opam exec -- make
  - mkdir -p ocaml-platform/4.07.0-1/ubuntu-18.04/amd64 && cp _build/default/output/* ocaml-platform/4.07.0-1/ubuntu-18.04/amd64
  artifacts:
    paths:
      - ocaml-platform
  tags:
    - docker
    - amd64
alpine-3.7-amd64:
  image: ocaml/opam2:alpine-3.7-opam
  stage: build
  script:
  - sudo apk add --update pkgconfig m4
  - opam init -ya --disable-sandboxing
  - opam install -y ocamlfind dune
  - opam exec -- make
  - mkdir -p ocaml-platform/4.07.0-1/alpine-3.7/amd64 && cp _build/default/output/* ocaml-platform/4.07.0-1/alpine-3.7/amd64
  artifacts:
    paths:
      - ocaml-platform
  tags:
    - docker
    - amd64
centos-7-amd64:
  image: ocaml/opam2:centos-7-opam
  stage: build
  script:
  - sudo yum -y install m4 pkg-config
  - opam init -ya --disable-sandboxing
  - opam install -y ocamlfind dune
  - opam exec -- make
  - mkdir -p ocaml-platform/4.07.0-1/centos-7/amd64 && cp _build/default/output/* ocaml-platform/4.07.0-1/centos-7/amd64
  artifacts:
    paths:
      - ocaml-platform
  tags:
    - docker
    - amd64
fedora-28-amd64:
  image: ocaml/opam2:fedora-28-opam
  stage: build
  script:
  - sudo yum -y install m4 pkg-config
  - opam init -ya --disable-sandboxing
  - opam install -y ocamlfind dune
  - opam exec -- make
  - mkdir -p ocaml-platform/4.07.0-1/fedora-28/amd64 && cp _build/default/output/* ocaml-platform/4.07.0-1/fedora-28/amd64
  artifacts:
    paths:
      - ocaml-platform
  tags:
    - docker
    - amd64
macos-amd64:
  stage: build
  script:
  - brew install ocaml/ocaml/opam@2
  - rm -rf ~/.opam
  - opam init -ya 
  - opam install -y ocamlfind dune
  - opam exec -- make
  - mkdir -p ocaml-platform/4.07.0-1/macos/arm64 && cp _build/default/output/* ocaml-platform/4.07.0-1/macos/arm64
  artifacts:
    paths:
      - ocaml-platform
  tags:
    - macos
gather-binaries:
  stage: gather
  script:
  - tar -zcvf ocaml-platform-$CI_COMMIT_SHA.tar.gz ocaml-platform
  artifacts:
    paths:
      - ocaml-platform-$CI_COMMIT_SHA.tar.gz
stages:
  - build
  - gather
