language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash ./.travis-docker.sh
env:
  global:
    - PACKAGE=mdx
    - DISTRO=debian-stable
  matrix:
    - OCAML_VERSION=4.02.3
    - OCAML_VERSION=4.03.0
    - OCAML_VERSION=4.04
    - OCAML_VERSION=4.05
    - OCAML_VERSION=4.06
    - OCAML_VERSION=4.07
    - OCAML_VERSION=4.08
    - OCAML_VERSION=4.09
