sudo: required
language: generic

env:
  - COMPILER=4.02.3
  - COMPILER=4.03.0
  - COMPILER=4.04.2
  - COMPILER=4.05.0
  - COMPILER=4.06.1
  - COMPILER=4.07.1
  - COMPILER=4.08.0

before_script:
  - set -e
  - wget https://github.com/ocaml/opam/releases/download/2.0.5/opam-2.0.5-x86_64-linux
  - sudo mv opam-2.0.5-x86_64-linux /usr/local/bin/opam
  - sudo chmod a+x /usr/local/bin/opam
  - opam init -y --bare --disable-sandboxing --disable-shell-hook
  - "opam switch create . $COMPILER $REPOSITORIES --no-install"
  - eval `opam config env`
  - opam --version
  - ocaml -version
  - opam pin add --yes --no-action lwt_log .
  - opam install --yes --deps-only lwt_log

script:
  - make
  - opam lint

notifications:
  email:
    recipients:
      - antonbachin@yahoo.com
    on_success: always
    on_failure: always
