version: 2
jobs:
  build-fedora-28:
    docker:
      - image: ocaml/opam2:fedora-28-opam
    steps:
    - checkout
    - run: sudo yum -y install m4 pkg-config
    - run: opam init -ya --disable-sandboxing
    - run: opam install -y ocamlfind dune
    - run: opam exec -- make
  build-debian-9:
    docker:
      - image: ocaml/opam2:debian-9-opam
    steps:
    - checkout
    - run: sudo apt-get update && sudo apt-get -y install pkg-config m4
    - run: opam init -ya --disable-sandboxing
    - run: opam install -y ocamlfind dune
    - run: opam exec -- make
  build-ubuntu-1804:
    docker:
      - image: ocaml/opam2:ubuntu-18.04-opam
    steps:
    - checkout
    - run: sudo apt-get update && sudo apt-get -y install pkg-config m4
    - run: opam init -ya --disable-sandboxing
    - run: opam install -y ocamlfind dune
    - run: opam exec -- make
  build-alpine:
    docker:
      - image: ocaml/opam2:alpine-3.7-opam
    steps:
    - checkout
    - run: sudo apk add --update pkgconfig m4
    - run: opam init -ya --disable-sandboxing
    - run: opam install -y ocamlfind dune
    - run: opam exec -- make
  build-macos:
    macos:
      xcode: "9.0"
    environment:
      MACOSX_DEPLOYMENT_TARGET: "10.12"
      TERM: vt100
    steps:
    - checkout
    - run: brew install pkg-config m4
    - run: brew install ocaml/ocaml/opam@2
    - run: opam init -ya
    - run: opam install -y ocamlfind dune
    - run: opam exec -- make
workflows:
  version: 2
  build-platform:
    jobs:
    - build-macos
    - build-alpine
    - build-debian-9
    - build-ubuntu-18-04
    - build-fedora-28
