version: 2
jobs:
  build-fedora-28:
    docker:
      - image: ocaml/opam2:fedora-28-opam
    steps:
    - checkout
    - run: sudo yum -y install m4 pkg-config
    - run: opam init -ya --disable-sandboxing
    - run: opam install -y ocamlfind dune
    - run: opam exec -- make
    - store_artifacts:
        path: _build/default/output
        destination: ocaml-platform-fedora-28
  build-debian-9:
    docker:
      - image: ocaml/opam2:debian-9-opam
    steps:
    - checkout
    - run: sudo apt-get update && sudo apt-get -y install pkg-config m4
    - run: opam init -ya --disable-sandboxing
    - run: opam install -y ocamlfind dune
    - run: opam exec -- make
    - store_artifacts:
        path: _build/default/output
        destination: ocaml-platform-debian-9
  build-ubuntu-1804:
    docker:
      - image: ocaml/opam2:ubuntu-18.04-opam
    steps:
    - checkout
    - run: sudo apt-get update && sudo apt-get -y install pkg-config m4
    - run: opam init -ya --disable-sandboxing
    - run: opam install -y ocamlfind dune
    - run: opam exec -- make
    - run: mkdir ubuntu-1804 && cp _build/default/output/* ubuntu-1804/
    - persist_to_workspace:
       root: .
       paths: ubuntu-1804
  build-alpine:
    docker:
      - image: ocaml/opam2:alpine-3.7-opam
    steps:
    - checkout
    - run: sudo apk add --update pkgconfig m4
    - run: opam init -ya --disable-sandboxing
    - run: opam install -y ocamlfind dune
    - run: opam exec -- make
    - run: mkdir alpine && cp _build/default/output/* alpine/
    - persist_to_workspace:
       root: .
       paths: alpine
  build-macos:
    macos:
      xcode: "9.0"
    environment:
      MACOSX_DEPLOYMENT_TARGET: "10.12"
      TERM: vt100
    steps:
    - checkout
    - run: brew install pkg-config m4
    - run: brew install ocaml/ocaml/opam@2
    - run: opam init -ya
    - run: opam install -y ocamlfind dune
    - run: opam exec -- make
    - run: mkdir macos && cp _build/default/output/* macos/
    - persist_to_workspace:
       root: .
       paths: macos
  gather:
    docker:
      - image: ocaml/opam2:alpine-3.7-opam
    steps:
      - run: mkdir /root/ocaml-platform
      - attach_workspace:
          at: /root/ocaml-platform
      - store_artifacts:
          path: /root/ocaml-platform
          destination: ocaml-platform-4.07.0
workflows:
  version: 2
  build-platform:
    jobs:
    - build-macos
    - build-alpine
    - build-debian-9
    - build-ubuntu-1804
    - build-fedora-28
    - gather:
        requires:
        - build-macos
        - build-alpine
        - build-debian-9
        - build-ubuntu-1804
        - build-fedora-28
