version: 2
jobs:
  build-alpine:
    docker:
      - image: ocaml/opam2:alpine-3.7-opam
    branches:
      only:
        - master
    steps:
    - checkout
    - run: apk add --update pkg-config m4
    - run: opam init -ya
    - run: opam install -y ocamlfind dune
    - run: opam exec -- make
  build-macos:
    macos:
      xcode: "9.0"
    environment:
      MACOSX_DEPLOYMENT_TARGET: "10.12"
      TERM: vt100
    steps:
    - checkout
    - run: brew install pkg-config m4
    - run: brew install ocaml/ocaml/opam@2
    - run: opam init -ya
    - run: opam install -y ocamlfind dune
    - run: opam exec -- make
workflows:
  version: 2
  build-platform:
    jobs:
    - build-macos
    - build-alpine
