version: 2
jobs:
  build-fedora-28:
    docker:
      - image: ocaml/opam2:fedora-28-opam
    steps:
    - checkout
    - run: sudo yum -y install m4 pkg-config
    - run: opam init -ya --disable-sandboxing
    - run: opam exec -- make
    - run: mkdir -p ocaml-platform/4.07.0-1/fedora-28/amd64 && cp _build/default/output/* ocaml-platform/4.07.0-1/fedora-28/amd64
    - persist_to_workspace:
       root: .
       paths: ocaml-platform
  build-debian-9:
    docker:
      - image: ocaml/opam2:debian-9-opam
    steps:
    - checkout
    - run: sudo apt-get update && sudo apt-get -y install pkg-config m4
    - run: opam init -ya --disable-sandboxing
    - run: opam exec -- make
    - run: mkdir -p ocaml-platform/4.07.0-1/debian-9/amd64 && cp _build/default/output/* ocaml-platform/4.07.0-1/debian-9/amd64
    - persist_to_workspace:
       root: .
       paths: ocaml-platform
  build-ubuntu-1804:
    docker:
      - image: ocaml/opam2:ubuntu-18.04-opam
    steps:
    - checkout
    - run: sudo apt-get update && sudo apt-get -y install pkg-config m4
    - run: opam init -ya --disable-sandboxing
    - run: opam exec -- make
    - run: mkdir -p ocaml-platform/4.07.0-1/ubuntu-18.04/amd64 && cp _build/default/output/* ocaml-platform/4.07.0-1/ubuntu-18.04/amd64
    - persist_to_workspace:
       root: .
       paths: ocaml-platform
  build-alpine:
    docker:
      - image: ocaml/opam2:alpine-3.7-opam
    steps:
    - checkout
    - run: sudo apk add --update pkgconfig m4
    - run: opam init -ya --disable-sandboxing
    - run: opam exec -- make
    - run: mkdir alpine && cp _build/default/output/* alpine/
    - run: mkdir -p ocaml-platform/4.07.0-1/alpine-3.7/amd64 && cp _build/default/output/* ocaml-platform/4.07.0-1/alpine-3.7/amd64
    - persist_to_workspace:
       root: .
       paths: ocaml-platform
  build-macos:
    macos:
      xcode: "9.0"
    environment:
      MACOSX_DEPLOYMENT_TARGET: "10.12"
      TERM: vt100
    steps:
    - checkout
    - run: brew install pkg-config m4
    - run: brew install ocaml/ocaml/opam@2
    - run: opam init -ya
    - run: opam exec -- make
    - run: mkdir -p ocaml-platform/4.07.0-1/macos-10.12/amd64 && cp _build/default/output/* ocaml-platform/4.07.0-1/macos-10.12/amd64
    - persist_to_workspace:
       root: .
       paths: ocaml-platform
  gather:
    docker:
      - image: ocaml/opam2:alpine-3.7-opam
    steps:
      - run: mkdir /home/opam/ocaml-platform
      - attach_workspace:
          at: /home/opam/ocaml-platform
      - store_artifacts:
          path: /home/opam/ocaml-platform
          destination: ocaml-platform
workflows:
  version: 2
  build-platform:
    jobs:
    - build-macos
    - build-alpine
    - build-debian-9
    - build-ubuntu-1804
    - build-fedora-28
    - gather:
        requires:
        - build-macos
        - build-alpine
        - build-debian-9
        - build-ubuntu-1804
        - build-fedora-28
