language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
services:
  - docker
sudo: false
env:
  global:
    - PACKAGE="ppx_tools_versioned"
    - PRE_INSTALL_HOOK="cd /home/opam/opam-repository && git pull origin master && opam update -u -y"
    - DISTRO=ubuntu-16.04
  matrix:
    - OCAML_VERSION=4.02.3
    - OCAML_VERSION=4.03.0
    - OCAML_VERSION=4.04.2
    - OCAML_VERSION=4.05.0
    - OCAML_VERSION=4.06.1
    - OCAML_VERSION=4.07.1
    - OCAML_VERSION=4.08.0
