language: node_js
node_js:
  - "10.13.0"

matrix:
  include:
    - os: osx
      env: OCAML=4.08.1
    - os: osx
      env: ESY_BUILD=YES ESY__CACHE=/home/travis/.esy
    - os: linux
      env: OCAML=4.02.3
    - os: linux
      env: OCAML=4.02.3+buckle-master
    - os: linux
      env: OCAML=4.03.0
    - os: linux
      env: OCAML=4.04.2
    - os: linux
      env: OCAML=4.05.0
    - os: linux
      env: OCAML=4.06.1
    - os: linux
      env: OCAML=4.07.1
    - os: linux
      env: OCAML=4.08.1
    - os: linux
      env: OCAML=ocaml-variants.4.09.0+beta2 REPOSITORIES=--repositories=default,beta=git+https://github.com/ocaml/ocaml-beta-repository.git
    - os : linux
      env: ESY_BUILD=YES ESY__CACHE=/home/travis/.esy

  fast_finish: true

cache:
  directories:
    - $HOME/.opam
    - $HOME/.esy
    - $HOME/.nvm
    - ./_opam
    - ./_build/default

install:
  - ./test/ci/install-deps.sh
  - "if [[ $OCAML ]]; then eval `opam env`; fi"
  - ./test/ci/print-versions.sh

before_script:
  - ./test/ci/clean-scratch.sh

script: travis_wait 20 ./test/ci/build.sh

notifications:
  email:
    on_success: always
    on_failure: always
