language: generic

env:
  - SWITCH=system
  - SWITCH=4.03.0
  - SWITCH=4.04.2
  - SWITCH=4.05.0
  - SWITCH=4.06.1

before_script:
  - set -e
  - sudo add-apt-repository -y ppa:avsm/ocaml42+opam12
  - sudo apt-get update
  - sudo apt-get install ocaml-nox opam python-bs4
  - opam init -y --compiler $SWITCH
  - eval `opam config env`
  - ocaml -version

script:
  - opam pin add -y --no-action lambdasoup .
  - opam install -y --deps-only lambdasoup
  - opam install -y ounit
  - make test
  - make performance-test

notifications:
  email:
    recipients:
      - antonbachin@yahoo.com
    on_success: always
    on_failure: always
